Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F01_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F01_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F02_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F02_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F03_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F03_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F04_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F04_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F05_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F05_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F06_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F06_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F07_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F07_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F08_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F08_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F09_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F09_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F10_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F10_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F11_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F11_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F12_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F12_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F13_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F13_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F14_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F14_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F15_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F15_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F16_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F16_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F17_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F17_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F18_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F18_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F19_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F19_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F20_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F20_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F21_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F21_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F22_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F22_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F23_nipt
Rscript script/step4_HMM_dbi_mat_OR.bk.R workdir/output/F23_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F24_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F24_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F25_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F25_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F26_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F26_nipt
Rscript script/ workdir/output/
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F27_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F28_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F29_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F30_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F31_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F32_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F33_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F34_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F35_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F36_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F37_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F38_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F39_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F40_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F41_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F42_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F43_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F44_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F45_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F46_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F47_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F48_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F49_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F50_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F51_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F52_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F53_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F54_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F55_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F56_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F57_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F58_nipt
Rscript script/step4_HMM_dbi_pat_OR_0.02.R workdir/output/F59_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F27_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F28_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F29_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F30_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F31_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F32_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F33_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F34_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F35_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F36_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F37_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F38_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F39_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F40_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F41_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F42_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F43_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F44_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F45_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F46_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F47_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F48_nipt
Rscript script/step4_HMM_dbi_mat_OR.bk.R workdir/output/F49_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F50_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F51_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F52_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F53_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F54_nipt
Rscript script/step4_HMM_dbi_mat_OR.bk.R workdir/output/F55_nipt
Rscript script/step4_HMM_dbi_mat_OR.v2.R workdir/output/F56_nipt
Rscript script/step4_HMM_dbi_mat_OR.bk.R workdir/output/F57_nipt
Rscript script/step4_HMM_dbi_mat_OR.bk.R workdir/output/F58_nipt
Rscript script/step4_HMM_dbi_mat_OR.bk.R workdir/output/F59_nipt
